[versions]
compose = "1.11.1"
compose-material3 = "1.11.0-alpha07"
json5 = "0.5.0"
kotlin = "2.4.0"
kotlinx-serialization-json = "1.9.0"
r8 = "9.1.31"

[libraries]
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
json5 = { module = "li.songe:json5", version.ref = "json5" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
r8 = { module = "com.android.tools:r8", version.ref = "r8" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
